/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExcluirContaRouteImport } from './routes/excluir-conta'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedApolicesRouteImport } from './routes/_authenticated/apolices'
import { Route as AuthenticatedComissoesRouteImport } from './routes/_authenticated/comissoes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDonoRouteImport } from './routes/_authenticated/dono'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedRenovacoesRouteImport } from './routes/_authenticated/renovacoes'
import { Route as AuthenticatedSinistrosRouteImport } from './routes/_authenticated/sinistros'
import { Route as AuthenticatedVeiculosRouteImport } from './routes/_authenticated/veiculos'
import { Route as ApiMercadopagoRouteImport } from './routes/api/mercadopago'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes/index'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcluirContaRoute = ExcluirContaRouteImport.update({
  id: '/excluir-conta',
  path: '/excluir-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApolicesRoute = AuthenticatedApolicesRouteImport.update({
  id: '/apolices',
  path: '/apolices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComissoesRoute = AuthenticatedComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDonoRoute = AuthenticatedDonoRouteImport.update({
  id: '/dono',
  path: '/dono',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRenovacoesRoute = AuthenticatedRenovacoesRouteImport.update({
  id: '/renovacoes',
  path: '/renovacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSinistrosRoute = AuthenticatedSinistrosRouteImport.update({
  id: '/sinistros',
  path: '/sinistros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVeiculosRoute = AuthenticatedVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiMercadopagoRoute = ApiMercadopagoRouteImport.update({
  id: '/api/mercadopago',
  path: '/api/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/excluir-conta': typeof ExcluirContaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/apolices': typeof AuthenticatedApolicesRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dono': typeof AuthenticatedDonoRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/renovacoes': typeof AuthenticatedRenovacoesRoute
  '/sinistros': typeof AuthenticatedSinistrosRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/api/mercadopago': typeof ApiMercadopagoRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/excluir-conta': typeof ExcluirContaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/apolices': typeof AuthenticatedApolicesRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dono': typeof AuthenticatedDonoRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/renovacoes': typeof AuthenticatedRenovacoesRoute
  '/sinistros': typeof AuthenticatedSinistrosRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/api/mercadopago': typeof ApiMercadopagoRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/excluir-conta': typeof ExcluirContaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/apolices': typeof AuthenticatedApolicesRoute
  '/_authenticated/comissoes': typeof AuthenticatedComissoesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dono': typeof AuthenticatedDonoRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/renovacoes': typeof AuthenticatedRenovacoesRoute
  '/_authenticated/sinistros': typeof AuthenticatedSinistrosRoute
  '/_authenticated/veiculos': typeof AuthenticatedVeiculosRoute
  '/api/mercadopago': typeof ApiMercadopagoRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/excluir-conta'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/agenda'
    | '/apolices'
    | '/comissoes'
    | '/configuracoes'
    | '/dashboard'
    | '/dono'
    | '/leads'
    | '/relatorios'
    | '/renovacoes'
    | '/sinistros'
    | '/veiculos'
    | '/api/mercadopago'
    | '/clientes/$id'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/excluir-conta'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/agenda'
    | '/apolices'
    | '/comissoes'
    | '/configuracoes'
    | '/dashboard'
    | '/dono'
    | '/leads'
    | '/relatorios'
    | '/renovacoes'
    | '/sinistros'
    | '/veiculos'
    | '/api/mercadopago'
    | '/clientes/$id'
    | '/clientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/excluir-conta'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/_authenticated/agenda'
    | '/_authenticated/apolices'
    | '/_authenticated/comissoes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/dono'
    | '/_authenticated/leads'
    | '/_authenticated/relatorios'
    | '/_authenticated/renovacoes'
    | '/_authenticated/sinistros'
    | '/_authenticated/veiculos'
    | '/api/mercadopago'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExcluirContaRoute: typeof ExcluirContaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TermosRoute: typeof TermosRoute
  ApiMercadopagoRoute: typeof ApiMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excluir-conta': {
      id: '/excluir-conta'
      path: '/excluir-conta'
      fullPath: '/excluir-conta'
      preLoaderRoute: typeof ExcluirContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apolices': {
      id: '/_authenticated/apolices'
      path: '/apolices'
      fullPath: '/apolices'
      preLoaderRoute: typeof AuthenticatedApolicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comissoes': {
      id: '/_authenticated/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof AuthenticatedComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dono': {
      id: '/_authenticated/dono'
      path: '/dono'
      fullPath: '/dono'
      preLoaderRoute: typeof AuthenticatedDonoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/renovacoes': {
      id: '/_authenticated/renovacoes'
      path: '/renovacoes'
      fullPath: '/renovacoes'
      preLoaderRoute: typeof AuthenticatedRenovacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sinistros': {
      id: '/_authenticated/sinistros'
      path: '/sinistros'
      fullPath: '/sinistros'
      preLoaderRoute: typeof AuthenticatedSinistrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veiculos': {
      id: '/_authenticated/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof AuthenticatedVeiculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/mercadopago': {
      id: '/api/mercadopago'
      path: '/api/mercadopago'
      fullPath: '/api/mercadopago'
      preLoaderRoute: typeof ApiMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedApolicesRoute: typeof AuthenticatedApolicesRoute
  AuthenticatedComissoesRoute: typeof AuthenticatedComissoesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDonoRoute: typeof AuthenticatedDonoRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedRenovacoesRoute: typeof AuthenticatedRenovacoesRoute
  AuthenticatedSinistrosRoute: typeof AuthenticatedSinistrosRoute
  AuthenticatedVeiculosRoute: typeof AuthenticatedVeiculosRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedApolicesRoute: AuthenticatedApolicesRoute,
  AuthenticatedComissoesRoute: AuthenticatedComissoesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDonoRoute: AuthenticatedDonoRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedRenovacoesRoute: AuthenticatedRenovacoesRoute,
  AuthenticatedSinistrosRoute: AuthenticatedSinistrosRoute,
  AuthenticatedVeiculosRoute: AuthenticatedVeiculosRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ExcluirContaRoute: ExcluirContaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TermosRoute: TermosRoute,
  ApiMercadopagoRoute: ApiMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
